### ISSUE TITLE
manage.py create_tenant_superuser results in argparse.ArgumentError on the string --schema

### ISSUE THREAD

**Issue by helgiborg** [django-tenants/django-tenants#1003]
When I run:
`python manage.py create_tenant_superuser`

in terminal, I get the following error stacktrace:

```
$ python manage.py create_tenant_superuser 
Traceback (most recent call last):
  File "/home/helgiborg/code_registration.git/django_registration/manage.py", line 22, in <module>
    main()
  File "/home/helgiborg/code_registration.git/django_registration/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/helgiborg/.virtualenvs/registration_django_reg/lib/python3.10/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/helgiborg/.virtualenvs/registration_django_reg/lib/python3.10/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/helgiborg/.virtualenvs/registration_django_reg/lib/python3.10/site-packages/django/core/management/base.py", line 404, in run_from_argv
    parser = self.create_parser(argv[0], argv[1])
  File "/home/helgiborg/.virtualenvs/registration_django_reg/lib/python3.10/site-packages/django/core/management/base.py", line 367, in create_parser
    self.add_arguments(parser)
  File "/home/helgiborg/.virtualenvs/registration_django_reg/lib/python3.10/site-packages/django_tenants/management/commands/__init__.py", line 128, in add_arguments
    self.command_instance.add_arguments(parser)
  File "/home/helgiborg/.virtualenvs/registration_django_reg/lib/python3.10/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 81, in add_arguments
    parser.add_argument(
  File "/usr/local/lib/python3.10/argparse.py", line 1448, in add_argument
    return self._add_action(action)
  File "/usr/local/lib/python3.10/argparse.py", line 1814, in _add_action
    self._optionals._add_action(action)
  File "/usr/local/lib/python3.10/argparse.py", line 1650, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File "/usr/local/lib/python3.10/argparse.py", line 1462, in _add_action
    self._check_conflict(action)
  File "/usr/local/lib/python3.10/argparse.py", line 1599, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "/usr/local/lib/python3.10/argparse.py", line 1608, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
argparse.ArgumentError: argument --schema: conflicting option string: --schema
```

Python version: Python 3.10.13 (main, Sep 21 2023, 16:06:19) [GCC 11.4.0] on linux
Libraries:
```
$ pip freeze
annotated-types==0.6.0
asgiref==3.7.2
defusedxml==0.7.1
diff-match-patch==20230430
Django==4.2.7
django-import-export==3.3.1
django-tenants==3.6.1
et-xmlfile==1.1.0
json5==0.9.14
MarkupPy==1.14
odfpy==1.4.1
openpyxl==3.1.2
psycopg2==2.9.7
pydantic==2.5.2
pydantic-settings==2.1.0
pydantic_core==2.14.5
python-dotenv==1.0.0
PyYAML==6.0.1
sqlparse==0.4.4
tablib==3.5.0
typing_extensions==4.9.0
Unidecode==1.3.7
xlrd==2.0.1
xlwt==1.3.0
```

**Comment by tomturner** [comment]
Closing as part of a backlog tidy-up — not because the report was wrong, but because it can no longer be acted on as it stands.

This has been inactive for some years and a great deal has changed underneath it: `clone_schema` has been replaced wholesale from upstream pg-clone-schema, psycopg3 is now the default driver, and the supported range is Django 4.2 / 5.2 / 6.0 on PostgreSQL 14–17. There's a fair chance this no longer reproduces.

If it still happens on **3.12.0**, please reopen with the django-tenants and Django versions, the PostgreSQL version, and the steps to reproduce — with that I can actually chase it down.

Thanks for reporting it.
