### ISSUE TITLE
ValueError: Empty module name

### ISSUE THREAD

**Issue by fabiodeabreuaraujo** [django-tenants/django-tenants#1098]
Hi,

I have some apps that I want to serve on different domains. I want them to run on the same server but have different hostnames and different URLs, while keeping the possibility of integrating the databases (e.g. a personal budget app that integrates with a shopping list app).

With those requirements, I decided to implement django-tenants with multi types tenants, so I have a "personal budget" tenant type with the personal_budget app installed, a "shopping list" tenant with the shopping_list app installed and a "public" type tenant with shared data.

The problem is: I have tried several approaches for testing, but everytime I call django.urls reverse function, I get the following error.

```python
ERROR: test_user_profile_view (tests.unit.user.test_tenant.BaseSetup.test_user_profile_view)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "...\tests\unit\user\test_tenant.py", line 22, in test_user_profile_view
    response = self.c.get(reverse('signup'))
                          ^^^^^^^^^^^^^^^^^
  File "...\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...\Lib\site-packages\django\urls\resolvers.py", line 749, in _reverse_with_prefix
    self._populate()
  File "...\Lib\site-packages\django\urls\resolvers.py", line 548, in _populate
    for url_pattern in reversed(self.url_patterns):
                                ^^^^^^^^^^^^^^^^^
  File "...\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "...\Lib\site-packages\django\urls\resolvers.py", line 718, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
                       ^^^^^^^^^^^^^^^^^^^
  File "...\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "...\Lib\site-packages\django\urls\resolvers.py", line 711, in urlconf_module
    return import_module(self.urlconf_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1201, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1114, in _sanity_check
ValueError: Empty module name

----------------------------------------------------------------------
```

I'm not sure why the import_module was called on the global python installation while all the others were on my virtualenv, but that might be part of the problem.

The approaches I've tried include creating a test file exactly like the example in [here](https://django-tenants.readthedocs.io/en/latest/test.html) and using the same settings file (with adaptations) as in the dts_test_project. This returns the same error.

Moreover, I use pytest in my projects and wouldn't like to have to stop.

Can someone please help me identify the problem and make my tests work with pytest?

**Comment by himilou** [comment]
curious to know  if you ever found an answer for this. Im having this issue in a django project using the django extension runserver command to call a script that does initial db population. 
Most solutions to this find empty strings in the settings file but this is not the case for me.

**Comment by himilou** [comment]
My similar experience when using djangoextensions runscript
  File "<frozen importlib._bootstrap>", line 1203, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1116, in _sanity_check
ValueError: Empty module name

this was caused by executing the command as such
 python .\manage.py runscript .\Scripts\setup

by removing the full path the error went away
 python .\manage.py runscript setup

for the above to work you must have your script ( i.e. setup.py ) located in a scripts\ subdirectory from the project base dir 
project
|
\scripts\setup.py
|
manage.py
