### ISSUE TITLE
Missing psycopg2 requirement manage.py migrate

### ISSUE THREAD

**Issue by atodorov** [django-tenants/django-tenants#336]
The change from this commit https://github.com/tomturner/django-tenants/commit/4e005ccb86bc38922226c268e0fa4c7d8a1d0a69

and the recently released 3.0.0 version causes existing apps to break. For example: 
https://travis-ci.org/kiwitcms/tenants/builds/635073127

```
./manage.py migrate

Traceback (most recent call last):

  File "./manage.py", line 12, in <module>

    execute_from_command_line(sys.argv)

  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line

    utility.execute()

  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/django/core/management/__init__.py", line 377, in execute

    django.setup()

  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/django/__init__.py", line 24, in setup

    apps.populate(settings.INSTALLED_APPS)

  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/django/apps/registry.py", line 114, in populate

    app_config.import_models()

  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/django/apps/config.py", line 211, in import_models

    self.models_module = import_module(models_module_name)

  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/importlib/__init__.py", line 126, in import_module

    return _bootstrap._gcd_import(name[level:], package, level)

  File "<frozen importlib._bootstrap>", line 994, in _gcd_import

  File "<frozen importlib._bootstrap>", line 971, in _find_and_load

  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked

  File "<frozen importlib._bootstrap_external>", line 678, in exec_module

  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/django_tenants/models.py", line 8, in <module>

    from .postgresql_backend.base import _check_schema_name

  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/django_tenants/postgresql_backend/base.py", line 11, in <module>

    import psycopg2

ModuleNotFoundError: No module named 'psycopg2'
```

@tomturner can you elaborate on why this requirements was removed and also what is the expected way to use django_tenants then? I don't see any info as to what necessitated the removal and nothing obvious in the docs to instruct the user to install the library. Yet in `requirements.txt` you still have this as a dependency. 

Edit: `.travis.yml` also contains an explicit `pip install psycopg2` and this is why it isn't failing.

FTR this is blocking an upgrade to django-tenants 3.0.0 and Django 3.0 respectively for us.

I am happy to contribute a PR but need to know the background of this issue.

**Comment by SamNgu** [comment]
https://github.com/tomturner/django-tenants/issues/317
