### ISSUE TITLE
Wagtail migration fails when using django-tenants

### ISSUE THREAD

**Issue by pyfabriz** [django-tenants/django-tenants#436]
I'm trying to set-up a Wagtail-based SaaS application using `django-tenants` in order to have a single Postgres schema for each tenant.

I have installed django-tenants strictly following documentation on ReadTheDocs and I successfully managed to migrate the public schema. 

However, when I add the first tenant via Django Admin, migration `wagtailcore.0037_set_page_owner_editable` fails with the following error:
```
tenants_1  | Applying wagtailcore.0037_set_page_owner_editable...
db_1       | ERROR:  cannot ALTER TABLE "wagtailcore_page" because it has pending trigger events
db_1       | STATEMENT:  SET CONSTRAINTS "wagtailcore_page_owner_id_fbf7c332_fk_auth_user_id" IMMEDIATE; ALTER TABLE "wagtailcore_page" DROP CONSTRAINT "wagtailcore_page_owner_id_fbf7c332_fk_auth_user_id"
db_1       | ERROR:  cannot DROP TABLE "wagtailcore_groupcollectionpermission" because it has pending trigger events
db_1       | STATEMENT:  DROP SCHEMA "tenant_galilei" CASCADE
tenants_1  | Internal Server Error: /django-admin/customers/client/add/
tenants_1  | Traceback (most recent call last):
tenants_1  |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
tenants_1  |     return self.cursor.execute(sql, params)
tenants_1  | psycopg2.errors.ObjectInUse: cannot ALTER TABLE "wagtailcore_page" because it has pending trigger events
tenants_1  | Internal Server Error: /django-admin/customers/client/add/
tenants_1  | Traceback (most recent call last):
tenants_1  |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
tenants_1  |     return self.cursor.execute(sql, params)
tenants_1  | psycopg2.errors.ObjectInUse: cannot ALTER TABLE "wagtailcore_page" because it has pending trigger events
tenants_1  | 
tenants_1  | 
tenants_1  | The above exception was the direct cause of the following exception:
tenants_1  | 
tenants_1  | Traceback (most recent call last):
tenants_1  |   File "/app/django_tenants/models.py", line 103, in save
tenants_1  |     self.create_schema(check_if_exists=True, verbosity=verbosity)
tenants_1  |   File "/app/django_tenants/models.py", line 194, in create_schema
tenants_1  |     verbosity=verbosity)
tenants_1  |   File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 148, in call_command
tenants_1  |     return command.execute(*args, **defaults)
tenants_1  |   File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
tenants_1  |     output = self.handle(*args, **options)
tenants_1  |   File "/app/django_tenants/management/commands/migrate_schemas.py", line 63, in handle
tenants_1  |     executor.run_migrations(tenants=tenants)
tenants_1  |   File "/app/django_tenants/migration_executors/standard.py", line 15, in run_migrations
tenants_1  |     run_migrations(self.args, self.options, self.codename, schema_name, idx=idx, count=len(tenants))
tenants_1  |   File "/app/django_tenants/migration_executors/base.py", line 36, in run_migrations
tenants_1  |     MigrateCommand(stdout=stdout, stderr=stderr).execute(*args, **options)
tenants_1  |   File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
tenants_1  |     output = self.handle(*args, **options)
tenants_1  |   File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 83, in wrapped
tenants_1  |     res = handle_func(*args, **kwargs)
tenants_1  |   File "/usr/local/lib/python3.7/site-packages/django/core/management/commands/migrate.py", line 234, in handle
tenants_1  |     fake_initial=fake_initial,
tenants_1  |   File "/usr/local/lib/python3.7/site-packages/django/db/migrations/executor.py", line 117, in migrate
tenants_1  |     state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
tenants_1  |   File "/usr/local/lib/python3.7/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
tenants_1  |     state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
tenants_1  |   File "/usr/local/lib/python3.7/site-packages/django/db/migrations/executor.py", line 245, in apply_migration
tenants_1  |     state = migration.apply(state, schema_editor)
tenants_1  |   File "/usr/local/lib/python3.7/site-packages/django/db/migrations/migration.py", line 124, in apply
tenants_1  |     operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
tenants_1  |   File "/usr/local/lib/python3.7/site-packages/django/db/migrations/operations/fields.py", line 249, in database_forwards
tenants_1  |     schema_editor.alter_field(from_model, from_field, to_field)
tenants_1  |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/schema.py", line 535, in alter_field
tenants_1  |     old_db_params, new_db_params, strict)
tenants_1  |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/postgresql/schema.py", line 124, in _alter_field
tenants_1  |     new_db_params, strict,
tenants_1  |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/schema.py", line 552, in _alter_field
tenants_1  |     self.execute(self._delete_fk_sql(model, fk_name))
tenants_1  |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/schema.py", line 137, in execute
tenants_1  |     cursor.execute(sql, params)
tenants_1  |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 99, in execute
tenants_1  |     return super().execute(sql, params)
tenants_1  |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 67, in execute
tenants_1  |     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
tenants_1  |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
tenants_1  |     return executor(sql, params, many, context)
tenants_1  |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
tenants_1  |     return self.cursor.execute(sql, params)
tenants_1  |   File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
tenants_1  |     raise dj_exc_value.with_traceback(traceback) from exc_value
tenants_1  |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
tenants_1  |     return self.cursor.execute(sql, params)
tenants_1  | django.db.utils.OperationalError: cannot ALTER TABLE "wagtailcore_page" because it has pending trigger events
tenants_1  | 
tenants_1  | 
tenants_1  | During handling of the above exception, another exception occurred:
tenants_1  | 
tenants_1  | Traceback (most recent call last):
tenants_1  |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 82, in _execute
tenants_1  |     return self.cursor.execute(sql)
tenants_1  | psycopg2.errors.ObjectInUse: cannot DROP TABLE "wagtailcore_groupcollectionpermission" because it has pending trigger events
tenants_1  | 
tenants_1  | 
tenants_1  | The above exception was the direct cause of the following exception:
tenants_1  | 
tenants_1  | Traceback (most recent call last):
tenants_1  |   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
tenants_1  |     response = get_response(request)
tenants_1  |   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
tenants_1  |     response = self.process_exception_by_middleware(e, request)
tenants_1  |   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
tenants_1  |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
tenants_1  |   File "/usr/local/lib/python3.7/site-packages/django/contrib/admin/options.py", line 606, in wrapper
tenants_1  |     return self.admin_site.admin_view(view)(*args, **kwargs)
tenants_1  |   File "/usr/local/lib/python3.7/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
tenants_1  |     response = view_func(request, *args, **kwargs)
tenants_1  |   File "/usr/local/lib/python3.7/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
tenants_1  |     response = view_func(request, *args, **kwargs)
tenants_1  |   File "/usr/local/lib/python3.7/site-packages/django/contrib/admin/sites.py", line 223, in inner
tenants_1  |     return view(request, *args, **kwargs)
tenants_1  |   File "/usr/local/lib/python3.7/site-packages/django/contrib/admin/options.py", line 1645, in add_view
tenants_1  |     return self.changeform_view(request, None, form_url, extra_context)
tenants_1  |   File "/usr/local/lib/python3.7/site-packages/django/utils/decorators.py", line 45, in _wrapper
tenants_1  |     return bound_method(*args, **kwargs)
tenants_1  |   File "/usr/local/lib/python3.7/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
tenants_1  |     response = view_func(request, *args, **kwargs)
tenants_1  |   File "/usr/local/lib/python3.7/site-packages/django/contrib/admin/options.py", line 1529, in changeform_view
tenants_1  |     return self._changeform_view(request, object_id, form_url, extra_context)
tenants_1  |   File "/usr/local/lib/python3.7/site-packages/django/contrib/admin/options.py", line 1572, in _changeform_view
tenants_1  |     self.save_model(request, new_object, form, not add)
tenants_1  |   File "/usr/local/lib/python3.7/site-packages/django/contrib/admin/options.py", line 1088, in save_model
tenants_1  |     obj.save()
tenants_1  |   File "/app/django_tenants/models.py", line 108, in save
tenants_1  |     self.delete(force_drop=True)
tenants_1  |   File "/app/django_tenants/models.py", line 153, in delete
tenants_1  |     self._drop_schema(force_drop)
tenants_1  |   File "/app/django_tenants/models.py", line 140, in _drop_schema
tenants_1  |     cursor.execute('DROP SCHEMA "%s" CASCADE' % self.schema_name)
tenants_1  |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 99, in execute
tenants_1  |     return super().execute(sql, params)
tenants_1  |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 67, in execute
tenants_1  |     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
tenants_1  |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
tenants_1  |     return executor(sql, params, many, context)
tenants_1  |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
tenants_1  |     return self.cursor.execute(sql, params)
tenants_1  |   File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
tenants_1  |     raise dj_exc_value.with_traceback(traceback) from exc_value
tenants_1  |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 82, in _execute
tenants_1  |     return self.cursor.execute(sql)
tenants_1  | django.db.utils.OperationalError: cannot DROP TABLE "wagtailcore_groupcollectionpermission" because it has pending trigger events
tenants_1  | 
```

Below you can find the failing Wagtail migration code:
```
# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-03 12:05
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0036_populate_page_last_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_pages', to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
    ]
```
My application is currently running on the following requirements versions:
```
Django==2.2.13
wagtail==2.8.2
django-tenants==3.1.0
```

I have both tried setting `TENANT_LIMIT_SET_CALLS ` to `True` and leaving it to its default `False` value, but I see no difference.
Without using django-tenants, migrations are executed correctly.

Is it possible that `_cursor()` function in `postgresql_backend.base.DatabaseWrapper` breaks the transaction by setting Postgres `search_path`?

Any help would be appreciated, thanks!

**Comment by jordanmt** [comment]
I'm running Wagtail and django-tenants together fairly well, but all of my tenants have been set up on the command line, not through the Django admin. I noticed that this is from /client/add, so I just tried to reproduce it by creating a client from the Django admin, and I'm seeing the same errors at the _wagtailcore.0037_set_page_owner_editable_ migration., e.g.:

`psycopg2.OperationalError: cannot ALTER TABLE "wagtailcore_page" because it has pending trigger events`

https://github.com/django-tenants/django-tenants/issues/476 provides some clues, as well as https://github.com/django-tenants/django-tenants/issues/93 which it refers to. In the latter they arrive at re-rolling migrations, but obviously that is not an option for migrations inside of project dependencies.

Setting immediate constraints (per https://github.com/django-tenants/django-tenants/issues/476) looks like it allows the migrations to continue successfully. I tested this out by overriding create_schema() on the client model. I hesitate to make any recommendations here, though, as I don't think I fully understand what's going on.

Are you able to create a tenant via the command line as well?

**Comment by KazuhiroKario** [comment]
I had the problem as like as yours.
But it was resolved by changing PostgreSQL's version.
I changed PostgreSQL's version from 13 to 11, and the problem never happened.
I'm not sure about that problem, but It's might be caused by PostgreSQL's version.

**Comment by FlogFr** [comment]
Currently running a Django project with `Django==5.0.14` ,  and `wagtail==6.4.1` , and `django-tenants==3.7.0` , and from a fresh new DB, the command runs OK :
```
./manage.py create_tenant --name tenant --domain-domain test_tenant.localhost --schema_name test_tenant
```

But if I try to create a simple Tenant from shell_plus :
```
In [1] : Client.objects.update_or_create(name="test", schema_name="test_tenant")
```

I get the same error, running on the `0040_page_draft_title` wagtail migrations : 
```
ObjectInUse: cannot ALTER TABLE "wagtailcore_page" because it has pending trigger events
```

**Comment by tomturner** [comment]
Closing as part of a backlog tidy-up — not because the report was wrong, but because it can no longer be acted on as it stands.

This has been inactive for some years and a great deal has changed underneath it: `clone_schema` has been replaced wholesale from upstream pg-clone-schema, psycopg3 is now the default driver, and the supported range is Django 4.2 / 5.2 / 6.0 on PostgreSQL 14–17. There's a fair chance this no longer reproduces.

If it still happens on **3.12.0**, please reopen with the django-tenants and Django versions, the PostgreSQL version, and the steps to reproduce — with that I can actually chase it down.

Thanks for reporting it.
