### ISSUE TITLE
Delete method test case fail if data=None not provided!

### ISSUE THREAD

**Issue by shivamzxzx** [django-tenants/django-tenants#477]
def test_delete_reports(self):
        some = somemodel.objects.first()
        self.client.credentials(HTTP_AUTHORIZATION="Token " + self.user.auth_token.key)
        response = self.client.delete(
            reverse("some_name", args=[some.id])
        )
        self.assertEqual(response.status_code, status.HTTP_204_NO_CONTENT)

Traceback
ERROR: test_delete_reports (reporting.tests.ReportingTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/operations_experience/reporting/tests.py", line 59, in test_delete_reports
    reverse("retailer_report_detail_view", args=[retailer_report.id])
  File "/.virtualenvs/ox/lib/python3.6/site-packages/tenant_schemas/test/client.py", line 80, in delete
    return super(TenantClient, self).delete(path, data, **extra)
  File "/.virtualenvs/ox/lib/python3.6/site-packages/rest_framework/test.py", line 324, in delete
    path, data=data, format=format, content_type=content_type, **extra)
  File "/.virtualenvs/ox/lib/python3.6/site-packages/rest_framework/test.py", line 224, in delete
    data, content_type = self._encode_data(data, format, content_type)
  File "/.virtualenvs/ox/lib/python3.6/site-packages/rest_framework/test.py", line 184, in _encode_data
    ret = renderer.render(data)
  File "/.virtualenvs/ox/lib/python3.6/site-packages/rest_framework/renderers.py", line 921, in render
    return encode_multipart(self.BOUNDARY, data)
  File "/.virtualenvs/ox/lib/python3.6/site-packages/django/test/client.py", line 194, in encode_multipart
    for (key, value) in data.items():
AttributeError: 'str' object has no attribute 'items'

----------------------------------------------------------------------
Ran 4 tests in 10.242s

FAILED (errors=1)
Destroying test database for alias 'default'...

**Comment by tomturner** [comment]
Closing as part of a backlog tidy-up — not because the report was wrong, but because it can no longer be acted on as it stands.

This has been inactive for some years and a great deal has changed underneath it: `clone_schema` has been replaced wholesale from upstream pg-clone-schema, psycopg3 is now the default driver, and the supported range is Django 4.2 / 5.2 / 6.0 on PostgreSQL 14–17. There's a fair chance this no longer reproduces.

If it still happens on **3.12.0**, please reopen with the django-tenants and Django versions, the PostgreSQL version, and the steps to reproduce — with that I can actually chase it down.

Thanks for reporting it.
