### ISSUE TITLE
Error when adding tenant via django admin interface

### ISSUE THREAD

**Issue by Warqus** [django-tenants/django-tenants#495]
When adding a tenant via the django admin interface, I get the following error:

```
Internal Server Error: /clients/public/django-admin/app_base/tenantclient/add/
Traceback (most recent call last):
  File "C:\Work\virtual_env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Work\virtual_env\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Work\virtual_env\lib\site-packages\django\contrib\admin\options.py", line 614, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\Work\virtual_env\lib\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Work\virtual_env\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Work\virtual_env\lib\site-packages\django\contrib\admin\sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "C:\Work\virtual_env\lib\site-packages\django\contrib\admin\options.py", line 1653, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "C:\Work\virtual_env\lib\site-packages\django\utils\decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Work\virtual_env\lib\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Work\virtual_env\lib\site-packages\django\contrib\admin\options.py", line 1534, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "C:\Work\virtual_env\lib\site-packages\django\contrib\admin\options.py", line 1585, in _changeform_view
    return self.response_add(request, new_object)
  File "C:\Work\virtual_env\lib\site-packages\django\contrib\admin\options.py", line 1179, in response_add
    current_app=self.admin_site.name,
  File "C:\Work\virtual_env\lib\site-packages\django\urls\base.py", line 55, in reverse
    app_list = resolver.app_dict[ns]
  File "C:\Work\virtual_env\lib\site-packages\django\urls\resolvers.py", line 522, in app_dict
    self._populate()
  File "C:\Work\virtual_env\lib\site-packages\django\urls\resolvers.py", line 457, in _populate
    p_pattern = url_pattern.pattern.regex.pattern
  File "C:\Work\virtual_env\lib\site-packages\django_tenants\urlresolvers.py", line 47, in regex
    return re.compile(self.tenant_prefix)
  File "C:\Work\virtual_env\lib\site-packages\django_tenants\urlresolvers.py", line 33, in tenant_prefix
    domain=connection.tenant.domain_subfolder,
AttributeError: 'FakeTenant' object has no attribute 'domain_subfolder'
```

This is probably due to not having set a domain yet, since that should be done after creating a tenant..

**Comment by MailaTshepang** [comment]
Same issue also

**Comment by tomturner** [comment]
Closing as part of a backlog tidy-up — not because the report was wrong, but because it can no longer be acted on as it stands.

This has been inactive for some years and a great deal has changed underneath it: `clone_schema` has been replaced wholesale from upstream pg-clone-schema, psycopg3 is now the default driver, and the supported range is Django 4.2 / 5.2 / 6.0 on PostgreSQL 14–17. There's a fair chance this no longer reproduces.

If it still happens on **3.12.0**, please reopen with the django-tenants and Django versions, the PostgreSQL version, and the steps to reproduce — with that I can actually chase it down.

Thanks for reporting it.
