### ISSUE TITLE
AttributeError: 'WSGIRequest' object has no attribute 'tenant'

### ISSUE THREAD

**Issue by rennols** [django-tenants/django-tenants#500]
So im trying to run tutorial tenant_subfolder_tutorial but got error

`Traceback (most recent call last):
  File "c:\Users\rennp\Downloads\Compressed\django-tenants-master\django-tenants-master\examples\tenant_subfolder_tutorial\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "c:\Users\rennp\Downloads\Compressed\django-tenants-master\django-tenants-master\examples\tenant_subfolder_tutorial\env\lib\site-packages\django\utils\deprecation.py", line 113, in __call__    response = self.process_request(request)
  File "C:\Users\rennp\Downloads\Compressed\django-tenants-master\django-tenants-master\examples\tenant_subfolder_tutorial\..\..\django_tenants\middleware\subfolder.py", line 55, in process_request
    self.setup_url_routing(request)
  File "C:\Users\rennp\Downloads\Compressed\django-tenants-master\django-tenants-master\examples\tenant_subfolder_tutorial\..\..\django_tenants\middleware\main.py", line 73, in setup_url_routing  
    if hasattr(settings, 'PUBLIC_SCHEMA_URLCONF') and request.tenant.schema_name == get_public_schema_name():
AttributeError: 'WSGIRequest' object has no attribute 'tenant'
[01/Dec/2020 17:00:55] "GET / HTTP/1.1" 500 73195
  File "c:\Users\rennp\Downloads\Compressed\django-tenants-master\django-tenants-master\examples\tenant_subfolder_tutorial\env\lib\site-packages\django\utils\deprecation.py", line 113, in __call__    response = self.process_request(request)            ter\examples\tenant_subfolder_tutorial\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inn
  File "C:\Users\rennp\Downloads\Compressed\django-tenants-master\django-tenants-master\examples\tenant_subfolder_tutorial\..\..\django_tenants\middleware\subfolder.py", line 55, in process_request                                                       ter\examples\tenant_subfolder_tutorial\env\lib\site-packages\django\utils\deprecation.py", line 113, in __call__
    self.setup_url_routing(request)
  File "C:\Users\rennp\Downloads\Compressed\django-tenants-master\django-tenants-master\examples\tenant_subfolder_tutorial\..\..\django_tenants\middleware\subfolder.py", line 55, in process_requester\examples\tenant_subfolder_tutorial\..\..\django_tenants\middleware\main.py", line 73, in setup_url_routing
    if hasattr(settings, 'PUBLIC_SCHEMA_URLCONF') and request.tenant.schema_name == ter\examples\tenant_subfolder_tutorial\..\..\django_tenants\middleware\main.py", line 73, in setup_url_routing  
get_public_schema_name():                                                           get_public_schema_name():
AttributeError: 'WSGIRequest' object has no attribute 'tenant'`

**Comment by kujbol** [comment]
@rennols Hey, did you resolved the problem? I have similar issue. I found a line which I had to change in the django-tenants, but I think I misconfigured some stuff and It should work out of the box

**Comment by gerald9784** [comment]
i am experiencing the same issue, @kujbol how did you fix it
