### ISSUE TITLE
'WSGIRequest' object has no attribute '_resource_closers' when trying to run example

### ISSUE THREAD

**Issue by sapkus** [django-tenants/django-tenants#520]
I am trying to run example with docker-compose.
python manage.py run 0.0.0.0:8088 server is running 404 is working, but when trying access tenant: test.localhost:8088 I get django error, wich looks like has to do something with middelaware.

Django version 3.1.3, using settings 'tenant_tutorial.settings'
Starting development server at http://0.0.0.0:8088/
Quit the server with CONTROL-C.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "/usr/local/lib/python3.8/site-packages/django/contrib/staticfiles/handlers.py", line 76, in __call__
    return self.application(environ, start_response)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/wsgi.py", line 133, in __call__
    response = self.get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 129, in get_response
    response._resource_closers.append(request.close)
AttributeError: **'WSGIRequest' object has no attribute '_resource_closers'**

I tried to downgrade to Django 2.2.12, got similar, but a bit different error:
Django version 2.2.12, using settings 'tenant_tutorial.settings'
Starting development server at http://0.0.0.0:8088/
Quit the server with CONTROL-C.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "/usr/local/lib/python3.8/site-packages/django/contrib/staticfiles/handlers.py", line 65, in __call__
    return self.application(environ, start_response)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 76, in get_response
    response._closable_objects.append(request)
**AttributeError: 'WSGIRequest' object has no attribute '_closable_objects'**

Tried with python3.8 - same. Also tried donwgrade gunicorn to 19.10 same.

**Comment by ericdaniel** [comment]
I had the same problem check this:    #514

**Comment by gerald9784** [comment]
If your using the current dev source code on github. I had the same issue. I solved it by reverting to commit  3936123c54086ac323d9aa144e69c16eb4f32e5d

**Comment by sapkus** [comment]
> I had the same problem check this: #514

This helped. Thank you

**Comment by tomturner** [comment]
This is an issue
