### ISSUE TITLE
Can't create superuser for public tenant when using custom User model

### ISSUE THREAD

**Issue by Jaquedeveloper** [django-tenants/django-tenants#526]
I have an application which uses a custom user model, **saasuser**:

**models.py**

    from django.db import models
    from django.utils.translation import gettext as _
    from django.contrib.auth.models import AbstractUser
    from django.contrib.auth.models import BaseUserManager

    def get_current_user(email):
        return User.objects.get(email=email)

    class UserManager(BaseUserManager):
        use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """Create and save a User with the given email and password."""
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        """Create and save a regular User with the given email and password."""
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        extra_fields.setdefault('user_type', 3)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        """Create and save a SuperUser with the given email and password."""
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)

    class User(AbstractUser):
        USER_TYPE_CHOICES = (
            (1, 'member'),
            (2, 'member staff'),
            (3, 'partner'),
            (4, 'partner staff'),
            (80, 'staff system'),
            (94, 'staff support'),
            (95, 'staff Commercial'),
            (96, 'staff Group'),
            (100, 'AnonymousUser'),
        )
        created_by = models.ForeignKey('self', on_delete=models.PROTECT, default=1,
                                   related_name="%(app_label)s_%(class)s_created_by_related",
                                   related_query_name="%(app_label)s_%(class)ss_created_by", )
        user_type = models.PositiveSmallIntegerField(verbose_name="tipo de usuário", choices=USER_TYPE_CHOICES, default=100)
        username = None
        email = models.EmailField(_('email address'), unique=True)
        USERNAME_FIELD = 'email'
        REQUIRED_FIELDS = []
        objects = UserManager()

        def __str__(self):              # __unicode__ on Python 2
            return self.email

        class Meta:
            ordering = ['-id']

I don't have access to the public tenant admin and I need to create a new superuser, in order to access it.
When I try to use the following command:

    python manage.py create_tenant_superuser --username=jaquedeveloper --schema=public

I receive the following error:

    Unknown command: 'create_tenant_superuser'. Did you mean createsuperuser?
    Type 'manage.py help' for usage.

And when I try to use `python manage.py createsuperuser`, after typing the user email I receive the following error:

    Traceback (most recent call last):
      File "/home/user/env/lib/python3.6/site-packages/django/db/backends/utils.py", line 86, in _execute
        return self.cursor.execute(sql, params)
    psycopg2.errors.UndefinedTable: relation "saasusers_user" does not exist
    LINE 1: ..._user"."user_type", "saasusers_user"."email" FROM "saasusers...
                                                             ^

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
       File "manage.py", line 21, in <module>
        main()
      File "manage.py", line 17, in main
        execute_from_command_line(sys.argv)
      File "/home/user/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
        utility.execute()
      File "/home/user/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 395, in execute
        self.fetch_command(subcommand).run_from_argv(self.argv)
      File "/home/user/env/lib/python3.6/site-packages/django/core/management/base.py", line 328, in run_from_argv
        self.execute(*args, **cmd_options)
      File "/home/user/env/lib/python3.6/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 79, in execute
        return super().execute(*args, **options)
      File "/home/user/env/lib/python3.6/site-packages/django/core/management/base.py", line 369, in execute
        output = self.handle(*args, **options)
      File "/home/user/env/lib/python3.6/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 113, in handle
        error_msg = self._validate_username(username, verbose_field_name, database)
      File "/home/user/env/lib/python3.6/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 234, in _validate_username
        self.UserModel._default_manager.db_manager(database).get_by_natural_key(username)
      File "/home/user/env/lib/python3.6/site-packages/django/contrib/auth/base_user.py", line 44, in get_by_natural_key
        return self.get(**{self.model.USERNAME_FIELD: username})
      File "/home/user/env/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
        return getattr(self.get_queryset(), name)(*args, **kwargs)
      File "/home/user/env/lib/python3.6/site-packages/django/db/models/query.py", line 411, in get
    num = len(clone)
      File "/home/user/env/lib/python3.6/site-packages/django/db/models/query.py", line 258, in __len__
    self._fetch_all()
      File "/home/user/env/lib/python3.6/site-packages/django/db/models/query.py", line 1261, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
      File "/home/user/env/lib/python3.6/site-packages/django/db/models/query.py", line 57, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
      File "/home/user/env/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1152, in execute_sql
        cursor.execute(sql, params)
      File "/home/user/env/lib/python3.6/site-packages/django/db/backends/utils.py", line 68, in execute
        return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
      File "/home/user/env/lib/python3.6/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
        return executor(sql, params, many, context)
      File "/home/user/env/lib/python3.6/site-packages/django/db/backends/utils.py", line 86, in _execute
        return self.cursor.execute(sql, params)
      File "/home/user/env/lib/python3.6/site-packages/django/db/utils.py", line 90, in __exit__
        raise dj_exc_value.with_traceback(traceback) from exc_value
      File "/home/user/env/lib/python3.6/site-packages/django/db/backends/utils.py", line 86, in _execute
        return self.cursor.execute(sql, params)
    django.db.utils.ProgrammingError: relation "saasusers_user" does not exist
    LINE 1: ..._user"."user_type", "saasusers_user"."email" FROM "saasusers...
                                                             ^

How can I fix or bypass it in order to create a superuser for the public tenant?

**Comment by tomturner** [comment]
you will need to show your settings for shared and tenant apps in order for someone to help

**Comment by Jaquedeveloper** [comment]
settings.py APPS

    SHARED_APPS = (
        'tenant_schemas',
        'customers',
        'django.contrib.contenttypes',
    )


    TENANT_APPS = (
        'corsheaders',
        'clearcache',
        'django.contrib.contenttypes',
        'django.contrib.auth',
        'django.contrib.sessions',
        'django.contrib.messages',
        'django.contrib.admin',
        'django.contrib.staticfiles',
        'saasusers',
        'core',
        'coreapi',
        'subscriptions',
        'postaladdresses',
        'persons',
        'corporations',
        'documents',
        'measurements',
        'recipients',
        'rest_framework',
    )

    TENANT_MODEL = "customers.Client"

    # Application definition

    INSTALLED_APPS = [
        'tenant_schemas',  # mandatory, should always be before any django app
        'corsheaders',
        'clearcache',
        'django.contrib.admin',
        'django.contrib.auth',
        'django.contrib.contenttypes',
        'django.contrib.sessions',
        'django.contrib.messages',
        'django.contrib.staticfiles',
        'core',
        'coreapi',
        'subscriptions',
        'postaladdresses',
        'persons',
        'corporations',
        'documents',
        'measurements',
        'recipients',
        'rest_framework',
    ]

    AUTH_USER_MODEL = 'saasusers.User'

**Comment by adnanmig** [comment]
@Jaquedeveloper Hi, I have a similar setup and the same problem. How did you resolve this issue?

**Comment by tdhillon-552** [comment]
anyone?
