### ISSUE TITLE
Using collectstatic_schemas in django 3.1.x fails

### ISSUE THREAD

**Issue by hanckmann** [django-tenants/django-tenants#580]
I am using **django-tenants==3.2.1**

When using collectstatic_schemas in combination with **django 3.0.14**, the command is successful.

When using collectstatic_schemas in combination with **django 3.1.8**, the command is fails as follows:

    $ python3.8 manage.py collectstatic_schemas --schema="schemaname"
    WARNING: Using remote configuration!
    Traceback (most recent call last):
      File "manage.py", line 43, in <module>
        main(remote)
      File "manage.py", line 39, in main
        execute_from_command_line(sys.argv)
      File "/home/dev/services/python-backend/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
        utility.execute()
      File "/home/dev/services/python-backend/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
        self.fetch_command(subcommand).run_from_argv(self.argv)
      File "/home/dev/services/python-backend/venv/lib/python3.8/site-packages/django/core/management/base.py", line 322, in run_from_argv
        parser = self.create_parser(argv[0], argv[1])
      File "/home/dev/services/python-backend/venv/lib/python3.8/site-packages/django/core/management/base.py", line 296, in create_parser
        self.add_arguments(parser)
      File "/home/dev/services/python-backend/venv/lib/python3.8/site-packages/django_tenants/management/commands/__init__.py", line 122, in add_arguments
        self.command_instance.add_arguments(parser)
      File "/home/dev/services/python-backend/venv/lib/python3.8/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 39, in add_arguments
        parser.add_argument(
      File "/usr/local/python3.8.8/lib/python3.8/argparse.py", line 1386, in add_argument
        return self._add_action(action)
      File "/usr/local/python3.8.8/lib/python3.8/argparse.py", line 1749, in _add_action
        self._optionals._add_action(action)
      File "/usr/local/python3.8.8/lib/python3.8/argparse.py", line 1590, in _add_action
        action = super(_ArgumentGroup, self)._add_action(action)
      File "/usr/local/python3.8.8/lib/python3.8/argparse.py", line 1400, in _add_action
        self._check_conflict(action)
      File "/usr/local/python3.8.8/lib/python3.8/argparse.py", line 1539, in _check_conflict
        conflict_handler(action, confl_optionals)
      File "/usr/local/python3.8.8/lib/python3.8/argparse.py", line 1548, in _handle_conflict_error
        raise ArgumentError(action, message % conflict_string)
    argparse.ArgumentError: argument --skip-checks: conflicting option string: --skip-checks

There is something with that --skip-checks options wrong. Note that I also get that error when I do not add --skip-checks as command line arguments.

**Comment by hanckmann** [comment]
Any update on this ticket?
It is really a strange one and I have no clue where to start. Especially since it nobody else seems to have this issue.
Note that I have this issue on my docker development system, as well as in production (which is not docker based and this a very different instance).

Do you require any additional input to have a look at this?

**Comment by hanckmann** [comment]
I have found a fix for this issue here: https://github.com/bernardopires/django-tenant-schemas/pull/650/commits/c25b27666afa9958399ba8d3b428024ae41b0c02#diff-f3d37263ffe8147dde1bee2da836b530bb3cac9ea6a4f4daa2f7ab7a506e2bfa

The fix is as simple as:
```
--- a/django_tenants/management/commands/collectstatic_schemas.py
+++ b/django_tenants/management/commands/collectstatic_schemas.py
@@ -3,4 +3,5 @@ from django.contrib.staticfiles.management.commands import collectstatic
 
 
 class Command(TenantWrappedCommand):
+    requires_system_checks = []
     COMMAND = collectstatic.Command
```

Could you please apply this change?
There are other changes among those patches (see the link above) as well. Maybe it is good to review those patches and possibly apply then to django-tenants as well.

**Comment by loctimize** [comment]
Hi! I still have the same issue with Django 3.2.4 and django_tenants 3.3.1. Although the above patch is applied. Any ideas?

**Comment by petriichuk** [comment]
Hey @loctimize have u managed to by pass the issue?

**Comment by Hanimir-san** [comment]
Not the best, but maybe it'll help someone. On Django version 3.2.5 and python 3.8, resolved this temporarily by editing `site-packages/django/core/management/base.py` and changing the following condition on line 391:

```
        if self.requires_system_checks and not options['skip_checks']:
```

changing it to this:

```
        if self.requires_system_checks and not options.get('skip_checks'):
```

That'll avoid any KeyError associated with skip_checks and just return None if doesn't exist.

Can't vouch for this entirely since it'll be overwritten when django is updated and I'm not sure what other side-effects it has on django management commands but it'll do for a quick fix.

**Comment by m7salam** [comment]
ok just for all of you out there who is looking for a solution for this I was able to fix this by overriding the command from django_tenants 

and this is the contents of the custom_command.py I made

```
from django_tenants.management.commands import TenantWrappedCommand
from django.contrib.staticfiles.management.commands import collectstatic


class Command(TenantWrappedCommand):
    requires_system_checks = []
    COMMAND = collectstatic.Command

    def add_arguments(self, parser):
        super().add_arguments(parser)
# this following line is the solution for it
        parser.add_argument(
            "--skip-checks",
            action="store_true",
            dest="skip_checks",
            default=False,
            help="Skip the checks.",
        )

```

so all you have to do is just do a custom command inside management/commands folder in any of your apps probably better in 'core' app if you have one or commons

then copy the above code in it and use that command instead until the maintainers fix it themselves !

thanks

**Comment by hanckmann** [comment]
I have put your fix into a pull request (I hope you do not mind)!

**Comment by tomturner** [comment]
Closing as part of a backlog tidy-up — not because the report was wrong, but because it can no longer be acted on as it stands.

This has been inactive for some years and a great deal has changed underneath it: `clone_schema` has been replaced wholesale from upstream pg-clone-schema, psycopg3 is now the default driver, and the supported range is Django 4.2 / 5.2 / 6.0 on PostgreSQL 14–17. There's a fair chance this no longer reproduces.

If it still happens on **3.12.0**, please reopen with the django-tenants and Django versions, the PostgreSQL version, and the steps to reproduce — with that I can actually chase it down.

Thanks for reporting it.
