### ISSUE TITLE
Tests failing: DB says object exists while it doesn't

### ISSUE THREAD

**Issue by atodorov** [django-tenants/django-tenants#621]
@tomturner I am having an issue with a test of mine (builds on top of django-tenants) which used to work till recently. The relevant changes are in the last commit at:
https://github.com/kiwitcms/github-app/pull/53/commits

The error I get is:

```
2021-06-22T14:21:25.5799783Z Traceback (most recent call last):
2021-06-22T14:21:25.5802004Z   File "/opt/hostedtoolcache/Python/3.8.10/x64/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
2021-06-22T14:21:25.5803210Z     return self.cursor.execute(sql, params)
2021-06-22T14:21:25.5804359Z psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "management_classification_name_key"
2021-06-22T14:21:25.5805498Z DETAIL:  Key (name)=(Classification 0) already exists.
2021-06-22T14:21:25.5805960Z 
2021-06-22T14:21:25.5806238Z 
2021-06-22T14:21:25.5806818Z The above exception was the direct cause of the following exception:
2021-06-22T14:21:25.5809890Z 
2021-06-22T14:21:25.5810297Z Traceback (most recent call last):
2021-06-22T14:21:25.5811127Z   File "/opt/hostedtoolcache/Python/3.8.10/x64/lib/python3.8/unittest/mock.py", line 1325, in patched
2021-06-22T14:21:25.5811871Z     return func(*newargs, **newkeywargs)
2021-06-22T14:21:25.5813344Z   File "/home/runner/work/github-app/github-app/tcms_github_app/tests/test_installation_repositories.py", line 128, in test_doesnt_crash_when_data_exists
2021-06-22T14:21:25.5814429Z     ProductFactory(name='kiwitcms-bot/IT')
2021-06-22T14:21:25.5815479Z   File "/opt/hostedtoolcache/Python/3.8.10/x64/lib/python3.8/site-packages/factory/base.py", line 40, in __call__
2021-06-22T14:21:25.5816207Z     return cls.create(**kwargs)
```

but from my debugging print statements it appears that there are no previous Product or Components objects: 

```
2021-06-22T14:21:25.5793146Z **** DEBUG: on tenant: fast will add a new product
2021-06-22T14:21:25.5794193Z 
2021-06-22T14:21:25.5794547Z *** DEBUG: Components= 0
```

so this baffles me how can the DB complain about a non-unique name constraint of there are no other records in this table. 

The only other test which executes is the one defined above the failing one and it is creating a Classification record but with a different name. However that appears to have been properly cleaned up by the time the next test method executes.

**Comment by atodorov** [comment]
Grrr, wrong debug statement. I see there's something present in the DB already, not sure why. Will investigate and close this issue once I know the root cause.

**Comment by atodorov** [comment]
I had 2 ClassificationFactory factories from different layered modules inside the project and I guess that didn't work well and the sequence numbers collided. Removing one of them solved my problem.

**Comment by atodorov** [comment]
I had 2 ClassificationFactory factories from different layered modules inside the project and I guess that didn't work well and the sequence numbers collided. Removing one of them solved my problem.
