### ISSUE TITLE
Error when adding SHOW_PUBLIC_IF_NO_TENANT_FOUND = True

### ISSUE THREAD

**Issue by macumhail** [django-tenants/django-tenants#692]
When I add the line: SHOW_PUBLIC_IF_NO_TENANT_FOUND = True to the settings file I get the following error in the terminal:
```
/Users/user/Desktop/testsite/config/settings.py changed, reloading.
Traceback (most recent call last):
  File "/Users/user/Desktop/testsite/manage.py", line 22, in <module>
    main()
  File "/Users/user/Desktop/testsite/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/Users/user/Desktop/testsite/.venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/Users/user/Desktop/testsite/.venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 345, in execute
    settings.INSTALLED_APPS
  File "/Users/user/Desktop/testsite/.venv/lib/python3.9/site-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/Users/user/Desktop/testsite/.venv/lib/python3.9/site-packages/django/conf/__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "/Users/user/Desktop/testsite/.venv/lib/python3.9/site-packages/django/conf/__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/Users/user/.pyenv/versions/3.9.2/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/user/Desktop/testsite/config/settings.py", line 121, in <module>
    SHOW_PUBLIC_IF_NO
NameError: name 'SHOW_PUBLIC_IF_NO' is not defined
```

**Comment by macumhail** [comment]
This was apparently an issue with my local machine. It is working correctly now.
