### ISSUE TITLE
Can't create schema with dash ('-') symbol and TENANT_BASE_SCHEMA

### ISSUE THREAD

**Issue by NevRA** [django-tenants/django-tenants#733]
Hey, everyone!

If Im using below configuration: 
`TENANT_BASE_SCHEMA = "template"`
`TENANT_CREATION_FAKES_MIGRATIONS = True`
and trying to create new schema via `manage.py create_tenant` or programmatically it works for names without dashes (e.g. test, test_test) but fails with test-test:

```
Traceback (most recent call last):
  File "/app/./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.9/site-packages/django_tenants/management/commands/create_tenant.py", line 69, in handle
    tenant = self.store_tenant(**tenant_data)
  File "/usr/local/lib/python3.9/site-packages/django_tenants/management/commands/create_tenant.py", line 106, in store_tenant
    tenant = get_tenant_model().objects.create(**fields)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 453, in create
    obj.save(force_insert=True, using=self.db)
  File "/usr/local/lib/python3.9/site-packages/django_tenants/models.py", line 111, in save
    self.create_schema(check_if_exists=True, verbosity=verbosity)
  File "/usr/local/lib/python3.9/site-packages/django_tenants/models.py", line 187, in create_schema
    clone_schema.clone_schema(base_schema, self.schema_name)
  File "/usr/local/lib/python3.9/site-packages/django_tenants/clone.py", line 740, in clone_schema
    cursor.execute(
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.InternalError: Action: Functions  Diagnostics: line=PL/pgSQL function clone_schema(text,text,boolean,boolean) line 413 at EXECUTE. 42601. syntax error at or near "-"
CONTEXT:  PL/pgSQL function clone_schema(text,text,boolean,boolean) line 669 at RAISE
```

What I'm doing wrong? 
Based on [this](https://github.com/django-tenants/django-tenants/commit/02af6fa9fdf17803c606663051c6cdbfa358edea) I supposed it should work 

Django 3.2.8
Tenants 3.4.2
Postgres 11.1

Thanks!

**Comment by akshaykolte88** [comment]
Hi @NevRA , Do you have any solution on this.? I'm also trying to create schema with "-" it gives me error. I'm using Django tenant and Django tenant schema.

**Comment by NevRA** [comment]
> Hi @NevRA , Do you have any solution on this.? I'm also trying to create schema with "-" it gives me error. I'm using Django tenant and Django tenant schema.
> 
> 

Unfortunately not

**Comment by tomturner** [comment]
Closing as part of a backlog tidy-up — not because the report was wrong, but because it can no longer be acted on as it stands.

This has been inactive for some years and a great deal has changed underneath it: `clone_schema` has been replaced wholesale from upstream pg-clone-schema, psycopg3 is now the default driver, and the supported range is Django 4.2 / 5.2 / 6.0 on PostgreSQL 14–17. There's a fair chance this no longer reproduces.

If it still happens on **3.12.0**, please reopen with the django-tenants and Django versions, the PostgreSQL version, and the steps to reproduce — with that I can actually chase it down.

Thanks for reporting it.
