### ISSUE TITLE
Django 4.1 breaks migrate_schemas (KeyError: 'prune')

### ISSUE THREAD

**Issue by auirarrazaval** [django-tenants/django-tenants#779]
In Django 4.1 a new option was added (`--prune`) which breaks the `migrate_schemas` (`django-tenants==3.4.2`). Thanks to [ this quick reply in stackoverflow](https://stackoverflow.com/a/72553621/16384621) I realize that it's probably something similar to what happened in  #259 a few years back when the `--plan` option was added to Django 2.2. For completeness, I'll also post the traceback here:

```
[standard:public] === Starting migration
Traceback (most recent call last):
  File "$directory/./manage.py", line 22, in <module>
    main()
  File "$directory/./manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "$venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "$/lib/python3.9/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "$venv/lib/python3.9/site-packages/django/core/management/base.py", line 402, in run_from_argv
    self.execute(*args, **cmd_options)
  File "$venv/lib/python3.9/site-packages/django/core/management/base.py", line 448, in execute
    output = self.handle(*args, **options)
  File "$venv/lib/python3.9/site-packages/django_tenants/management/commands/migrate_schemas.py", line 52, in handle
    executor.run_migrations(tenants=[self.PUBLIC_SCHEMA_NAME])
  File "$venv/lib/python3.9/site-packages/django_tenants/migration_executors/standard.py", line 11, in run_migrations
    run_migrations(self.args, self.options, self.codename, self.PUBLIC_SCHEMA_NAME)
  File "$venv/lib/python3.9/site-packages/django_tenants/migration_executors/base.py", line 53, in run_migrations
    MigrateCommand(stdout=stdout, stderr=stderr).execute(*args, **options)
  File "$venv/lib/python3.9/site-packages/django/core/management/base.py", line 448, in execute
    output = self.handle(*args, **options)
  File "$venv/lib/python3.9/site-packages/django/core/management/base.py", line 96, in wrapped
    res = handle_func(*args, **kwargs)
  File "$venv/lib/python3.9/site-packages/django/core/management/commands/migrate.py", line 188, in handle
    if options["prune"]:
KeyError: 'prune'
```

The fix seems to just the `--prune` option to the parser of `migrate_schemas`, so I'll make a PR soon doing exactly that

**Comment by mario-moreira** [comment]
This can be closed now, right?
