### ISSUE TITLE
collect static file without django tenants db connection

### ISSUE THREAD

**Issue by kalyanakannan** [django-tenants/django-tenants#853]
I need to collect static files without connecting to the database to dockerize my application. when I run `python manage.py collectstatic --no-input` . 

while doing the docker build I am getting the following error

```
Traceback (most recent call last):
  File "C:\projects\test-env\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\projects\test-env\lib\site-packages\django\db\backends\sqlite3\base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: information_schema.tables

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\projects\test-app\test\manage.py", line 22, in <module>
    main()
  File "C:\projects\test-app\test\manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "C:\projects\test-env\lib\site-packages\django\core\management\__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "C:\projects\test-env\lib\site-packages\django\core\management\__init__.py", line 395, in execute
    django.setup()
  File "C:\projects\test-env\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\projects\test-env\lib\site-packages\django\apps\registry.py", line 122, in populate
    app_config.ready()
  File "C:\projects\test-env\lib\site-packages\django_tenants\apps.py", line 46, in ready
    validate_extra_extensions()
  File "C:\projects\test-env\lib\site-packages\django_tenants\utils.py", line 272, in validate_extra_extensions
    cursor.execute(
  File "C:\projects\test-env\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "C:\projects\test-env\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\projects\test-env\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\projects\test-env\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\projects\test-env\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\projects\test-env\lib\site-packages\django\db\backends\sqlite3\base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: information_schema.tables
```

**Comment by tomturner** [comment]
Closing as part of a backlog tidy-up — not because the report was wrong, but because it can no longer be acted on as it stands.

This has been inactive for some years and a great deal has changed underneath it: `clone_schema` has been replaced wholesale from upstream pg-clone-schema, psycopg3 is now the default driver, and the supported range is Django 4.2 / 5.2 / 6.0 on PostgreSQL 14–17. There's a fair chance this no longer reproduces.

If it still happens on **3.12.0**, please reopen with the django-tenants and Django versions, the PostgreSQL version, and the steps to reproduce — with that I can actually chase it down.

Thanks for reporting it.
