### ISSUE TITLE
Deleting a tenant or migrating a model change causes errors

### ISSUE THREAD

**Issue by davidoh14** [django-tenants/django-tenants#925]
I've followed the setup instructions on the documentation and also followed along with the video tutorial. I'm pretty sure that I've set everything up right because I can create tenants and access tenanted django admins just fine, but the errors I'm running into make me think something is wrong with my setup. I've shared my settings.py at the end.

The first issue is that deleting a tenant causes this error:

```
Traceback (most recent call last):
  File "/Users/davidoh/virtualenvs/trail_api/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UndefinedTable: relation "websites_website" does not exist
LINE 1: ...e"."active", "websites_website"."created_at" FROM "websites_...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/davidoh/Workspace/trail_api/manage.py", line 26, in <module>
    main()
  File "/Users/davidoh/Workspace/trail_api/manage.py", line 22, in main
    execute_from_command_line(sys.argv)
  File "/Users/davidoh/virtualenvs/trail_api/lib/python3.11/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/Users/davidoh/virtualenvs/trail_api/lib/python3.11/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/davidoh/virtualenvs/trail_api/lib/python3.11/site-packages/django/core/management/base.py", line 402, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/davidoh/virtualenvs/trail_api/lib/python3.11/site-packages/django/core/management/base.py", line 448, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/davidoh/virtualenvs/trail_api/lib/python3.11/site-packages/django_tenants/management/commands/delete_tenant.py", line 25, in handle
    tenant.delete()
  File "/Users/davidoh/virtualenvs/trail_api/lib/python3.11/site-packages/django_tenants/models.py", line 162, in delete
    super().delete(*args, **kwargs)
  File "/Users/davidoh/virtualenvs/trail_api/lib/python3.11/site-packages/django/db/models/base.py", line 1117, in delete
    collector.collect([self], keep_parents=keep_parents)
  File "/Users/davidoh/virtualenvs/trail_api/lib/python3.11/site-packages/django/db/models/deletion.py", line 343, in collect
    if sub_objs:
  File "/Users/davidoh/virtualenvs/trail_api/lib/python3.11/site-packages/django/db/models/query.py", line 408, in __bool__
    self._fetch_all()
  File "/Users/davidoh/virtualenvs/trail_api/lib/python3.11/site-packages/django/db/models/query.py", line 1867, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/davidoh/virtualenvs/trail_api/lib/python3.11/site-packages/django/db/models/query.py", line 87, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/davidoh/virtualenvs/trail_api/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1398, in execute_sql
    cursor.execute(sql, params)
  File "/Users/davidoh/virtualenvs/trail_api/lib/python3.11/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/davidoh/virtualenvs/trail_api/lib/python3.11/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/davidoh/virtualenvs/trail_api/lib/python3.11/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/davidoh/virtualenvs/trail_api/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/Users/davidoh/virtualenvs/trail_api/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/davidoh/virtualenvs/trail_api/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.ProgrammingError: relation "websites_website" does not exist
LINE 1: ...e"."active", "websites_website"."created_at" FROM "websites_...
```

My TENANT_MODEL is companies_company, while websites_website is a tenanted app. I've confirmed that the websites_website table exists within each schema (except public of course). Why does deleting a tenant in the public schema, cause django to look for a table only within other schemas?

The second issue is when making a change to a model and then migrating returns this error:
```
Traceback (most recent call last):
  File "/Users/davidoh/virtualenvs/trail_api/lib/python3.11/site-packages/django/db/backends/utils.py", line 87, in _execute
    return self.cursor.execute(sql)
           ^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.DuplicateTable: relation "django_migrations" already exists


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/davidoh/virtualenvs/trail_api/lib/python3.11/site-packages/django/db/migrations/recorder.py", line 70, in ensure_schema
    editor.create_model(self.Migration)
  File "/Users/davidoh/virtualenvs/trail_api/lib/python3.11/site-packages/django/db/backends/base/schema.py", line 447, in create_model
    self.execute(sql, params or None)
  File "/Users/davidoh/virtualenvs/trail_api/lib/python3.11/site-packages/django/db/backends/base/schema.py", line 199, in execute
    cursor.execute(sql, params)
  File "/Users/davidoh/virtualenvs/trail_api/lib/python3.11/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/davidoh/virtualenvs/trail_api/lib/python3.11/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/davidoh/virtualenvs/trail_api/lib/python3.11/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/davidoh/virtualenvs/trail_api/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/Users/davidoh/virtualenvs/trail_api/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/davidoh/virtualenvs/trail_api/lib/python3.11/site-packages/django/db/backends/utils.py", line 87, in _execute
    return self.cursor.execute(sql)
           ^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.ProgrammingError: relation "django_migrations" already exists


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/davidoh/Workspace/trail_api/manage.py", line 26, in <module>
    main()
  File "/Users/davidoh/Workspace/trail_api/manage.py", line 22, in main
    execute_from_command_line(sys.argv)
  File "/Users/davidoh/virtualenvs/trail_api/lib/python3.11/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/Users/davidoh/virtualenvs/trail_api/lib/python3.11/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/davidoh/virtualenvs/trail_api/lib/python3.11/site-packages/django/core/management/base.py", line 402, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/davidoh/virtualenvs/trail_api/lib/python3.11/site-packages/django/core/management/base.py", line 448, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/davidoh/virtualenvs/trail_api/lib/python3.11/site-packages/django_tenants/management/commands/migrate_schemas.py", line 100, in handle
    executor.run_migrations(tenants=tenants)
  File "/Users/davidoh/virtualenvs/trail_api/lib/python3.11/site-packages/django_tenants/migration_executors/standard.py", line 14, in run_migrations
    run_migrations(self.args, self.options, self.codename, schema_name, idx=idx, count=len(tenants))
  File "/Users/davidoh/virtualenvs/trail_api/lib/python3.11/site-packages/django_tenants/migration_executors/base.py", line 48, in run_migrations
    migration_recorder.ensure_schema()
  File "/Users/davidoh/virtualenvs/trail_api/lib/python3.11/site-packages/django/db/migrations/recorder.py", line 72, in ensure_schema
    raise MigrationSchemaMissing(
django.db.migrations.exceptions.MigrationSchemaMissing: Unable to create the django_migrations table (relation "django_migrations" already exists
)
```

**settings.py**:

```
from pathlib import Path
import os
import sys
from .custom_filters import SkipStaticFiles

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# PROJECT_DIR = os.path.join(BASE_DIR, os.pardir)

# TENANT_APPS_DIR = os.path.join(PROJECT_DIR, os.pardir)
# sys.path.insert(0, TENANT_APPS_DIR)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = str(os.environ.get('DEBUG')) == "1"

ALLOWED_HOSTS = [********]

CORS_ALLOWED_ORIGINS = [*********]

if DEBUG:
    ALLOWED_HOSTS = ['*']
    CORS_ALLOW_ALL_ORIGINS = True

CORS_ALLOW_METHODS = [
    'GET',
    'OPTIONS',
    'POST',
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'origin',
    'user-agent',
    'x-api-key',  # add your custom header here
    'x-csrftoken',
]

# Application definition

SHARED_APPS = [
    'django_tenants',
    'whitenoise.runserver_nostatic', # keep this at top
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # third party packages
    'rest_framework',
    'corsheaders',

    # internal apps
    'companies',
]

TENANT_APPS = (
    'whitenoise.runserver_nostatic', # keep this at top
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',

    # third party packages
    'rest_framework',
    'corsheaders',
    
    #internal apps
    'apps.events',
    'apps.websites',
)

INSTALLED_APPS = list(SHARED_APPS) + [app for app in TENANT_APPS if app not in SHARED_APPS]

TENANT_MODEL = "companies.Company"

TENANT_DOMAIN_MODEL = "companies.Domain"

SHOW_PUBLIC_IF_NO_TENANT_FOUND = True

MIDDLEWARE = [
    'django_tenants.middleware.main.TenantMainMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'trail_api.urls'
PUBLIC_SCHEMA_URLCONF = 'trail_api.urls_public'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'trail_api.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django_tenants.postgresql_backend',
        'NAME': os.environ.get('DB_NAME'),
        'USER': os.environ.get('DB_USER'),
        'PASSWORD': os.environ.get('DB_PW'),
        'HOST': os.environ.get('DB_HOST'),
        'PORT': os.environ.get('DB_PORT'),
    }
}

DATABASE_ROUTERS = (
    'django_tenants.routers.TenantSyncRouter',
)


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
```

**Comment by HansvanHespen** [comment]
Got the same problem myself. Keep on stumbling on issues with django-tenants: cannot use subfolders, cannot use asgi, and cannot delete tenants. Python is supposed to be the most popular language of today, but I wonder what these people then do with it, if basic things don't work? I spend 30% of time programming, and 70% debugging errors of someone else. 

In my case the delete function of my model is called. Since there isn't any, it calls the delete function of the inherited models.py of django_tenants. It then drops the schema, allright.  From there is goes super().delete. There it searches correctly for csb_tenants_domain. Then it tries to do a select from a table in the schema that doesn't exist anymore, and looks for that table in the public schema, where it never existed of course. 

I wonder why it still does a select, in stead of immediately doing a delete of that particular row in the csb_tenants_domain table. Then, I ask myself, why would this result in a hard unhandled exception? 

Well, I will keep you posted if I have found anything. I have to admit that I start wondering if I shouldn't go back to delphi or c-sharp...

**Comment by HansvanHespen** [comment]
I found it! 

And it turns out I can't blame this one on bad coding of django-tenants. Honest is honest, this was my mistake. 

I had coded my class in the models.py of my tenant app like this:
class csbguest(TenantMixin):
    # type: csbtenants
    sbtenant = models.ForeignKey(csbtenants, on_delete=models.cascade, related_name='guests')

I was ill advised, but there you are. It makes sense to make that you want a foreign key if you want to link this class of the tenant to the list of tenants in the public schema.  And then, it also made sense to me that you do the on_delete in cascading.

What happens though, is that first the schema is deleted, and then the tenant is deleted. The deletion of the denant goes first through the delete_tenant.py of django_tenants, where a few checks are being done, and then it is being sent to the core of django, who doesn't know anything about schema's. And django does it job and goes looking for this table, of course in the public schema since it doesn't know any better, where it doesn't find it of course. 

By changing the line into this:
 csbtenant = models.ForeignKey(csbtenants, on_delete=models.DO_NOTHING, related_name='guests')

@davidoh14 tried with set_null and that didn't help for him. However, using the DO_NOTHING did the trick for me. 

Now it thoroughly delets the row of the specific tenant in the public schema, it deletes the line of the domain in the public schema, drops the schema of the tenant, and with that all of the tables inside of course.

Hence, if you create a class in the models.py of a tenant, use the DO_NOTHING, but if you create a class in the app of the public schema (client app in the example of Tom, and customers class) then you have to create it with the on_delete to CASCADE, because then they will not be automatically dropped by dropping the schema.  

So, there you are. It took me a couple of hours, but I learned a lot about how Django, the ORM and django_tenants work. 

Problem solved, what a great feeling!

**Comment by benshaji-sequoiaat** [comment]
> I found it!
> 
> And it turns out I can't blame this one on bad coding of django-tenants. Honest is honest, this was my mistake.
> 
> I had coded my class in the models.py of my tenant app like this: class csbguest(TenantMixin): # type: csbtenants sbtenant = models.ForeignKey(csbtenants, on_delete=models.cascade, related_name='guests')
> 
> I was ill advised, but there you are. It makes sense to make that you want a foreign key if you want to link this class of the tenant to the list of tenants in the public schema. And then, it also made sense to me that you do the on_delete in cascading.
> 
> What happens though, is that first the schema is deleted, and then the tenant is deleted. The deletion of the denant goes first through the delete_tenant.py of django_tenants, where a few checks are being done, and then it is being sent to the core of django, who doesn't know anything about schema's. And django does it job and goes looking for this table, of course in the public schema since it doesn't know any better, where it doesn't find it of course.
> 
> By changing the line into this: csbtenant = models.ForeignKey(csbtenants, on_delete=models.DO_NOTHING, related_name='guests')
> 
> @davidoh14 tried with set_null and that didn't help for him. However, using the DO_NOTHING did the trick for me.
> 
> Now it thoroughly delets the row of the specific tenant in the public schema, it deletes the line of the domain in the public schema, drops the schema of the tenant, and with that all of the tables inside of course.
> 
> Hence, if you create a class in the models.py of a tenant, use the DO_NOTHING, but if you create a class in the app of the public schema (client app in the example of Tom, and customers class) then you have to create it with the on_delete to CASCADE, because then they will not be automatically dropped by dropping the schema.
> 
> So, there you are. It took me a couple of hours, but I learned a lot about how Django, the ORM and django_tenants work.
> 
> Problem solved, what a great feeling!

I'm having the same issue now. When i try to delete a tenant using `./migrate delete_tenant` this issue "relation "app_table" does not exist". I believe this has started when I've added `Tenant` model as FK in other app's model as:

` customer = models.ForeignKey(Tenant, on_delete=models.CASCADE, related_name='customer_site')`

where `Tenant` is the actual Tenant model itself.

**Comment by benshaji-sequoiaat** [comment]
Read this solutuion: https://github.com/bernardopires/django-tenant-schemas/issues/695#issue-1897930338

**Comment by benshaji-sequoiaat** [comment]
Suppose: If your Tenant model is used by Student model as FK. 
i.e `models.ForeignKey(Tenant, on_delete=models.CASCADE, related_name='students')` << *THIS WILL cause the issue* due to reasons @HansvanHespen  suggested above and should be `models.DO_NOTHING`

**Comment by tomturner** [comment]
Closing as part of a backlog tidy-up — not because the report was wrong, but because it can no longer be acted on as it stands.

This has been inactive for some years and a great deal has changed underneath it: `clone_schema` has been replaced wholesale from upstream pg-clone-schema, psycopg3 is now the default driver, and the supported range is Django 4.2 / 5.2 / 6.0 on PostgreSQL 14–17. There's a fair chance this no longer reproduces.

If it still happens on **3.12.0**, please reopen with the django-tenants and Django versions, the PostgreSQL version, and the steps to reproduce — with that I can actually chase it down.

Thanks for reporting it.
