### ISSUE TITLE
relation "court_contacts" does not exist

### ISSUE THREAD

**Issue by darcivieira** [django-tenants/django-tenants#952]
Hey there!

I'm with unusual problem  here. I'm trying to delete a contact from a ManyToMany relationship that I have in a company table and I'm getting this error:

`
Internal Server Error: /api/v1/operational/company/t0G1-foxQzqFY_cF8pl9JQ/
Traceback (most recent call last):
  File "/home/junior/.local/share/virtualenvs/eos-ZVRZ_kFB/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedTable: relation "court_contacts" does not exist
LINE 1: ...s"."court_id", "court_contacts"."contact_id" FROM "court_con...
                                                             ^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/junior/.local/share/virtualenvs/eos-ZVRZ_kFB/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/junior/.local/share/virtualenvs/eos-ZVRZ_kFB/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/junior/.local/share/virtualenvs/eos-ZVRZ_kFB/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/junior/.local/share/virtualenvs/eos-ZVRZ_kFB/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/junior/.local/share/virtualenvs/eos-ZVRZ_kFB/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/junior/.local/share/virtualenvs/eos-ZVRZ_kFB/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/junior/.local/share/virtualenvs/eos-ZVRZ_kFB/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/junior/.local/share/virtualenvs/eos-ZVRZ_kFB/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/junior/.local/share/virtualenvs/eos-ZVRZ_kFB/lib/python3.10/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/junior/.local/share/virtualenvs/eos-ZVRZ_kFB/lib/python3.10/site-packages/rest_framework/mixins.py", line 82, in partial_update
    return self.update(request, *args, **kwargs)
  File "/home/junior/.local/share/virtualenvs/eos-ZVRZ_kFB/lib/python3.10/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/junior/.local/share/virtualenvs/eos-ZVRZ_kFB/lib/python3.10/site-packages/rest_framework/mixins.py", line 68, in update
    self.perform_update(serializer)
  File "/home/junior/.local/share/virtualenvs/eos-ZVRZ_kFB/lib/python3.10/site-packages/rest_framework/mixins.py", line 78, in perform_update
    serializer.save()
  File "/home/junior/.local/share/virtualenvs/eos-ZVRZ_kFB/lib/python3.10/site-packages/rest_framework/serializers.py", line 207, in save
    self.instance = self.update(self.instance, validated_data)
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/storage/Projetos/Panteu/eos/eosManager/serializers/generic_serializer.py", line 310, in update
    self.perform_update_contacts(instance, contacts_data)
  File "/storage/Projetos/Panteu/eos/eosManager/serializers/generic_serializer.py", line 156, in perform_update_contacts
    contact.delete()
  File "/home/junior/.local/share/virtualenvs/eos-ZVRZ_kFB/lib/python3.10/site-packages/django/db/models/base.py", line 1131, in delete
    collector.collect([self], keep_parents=keep_parents)
  File "/home/junior/.local/share/virtualenvs/eos-ZVRZ_kFB/lib/python3.10/site-packages/django/db/models/deletion.py", line 348, in collect
    if getattr(on_delete, "lazy_sub_objs", False) or sub_objs:
  File "/home/junior/.local/share/virtualenvs/eos-ZVRZ_kFB/lib/python3.10/site-packages/django/db/models/query.py", line 412, in __bool__
    self._fetch_all()
  File "/home/junior/.local/share/virtualenvs/eos-ZVRZ_kFB/lib/python3.10/site-packages/django/db/models/query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/junior/.local/share/virtualenvs/eos-ZVRZ_kFB/lib/python3.10/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "/home/junior/.local/share/virtualenvs/eos-ZVRZ_kFB/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1560, in execute_sql
    cursor.execute(sql, params)
  File "/home/junior/.local/share/virtualenvs/eos-ZVRZ_kFB/lib/python3.10/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
  File "/home/junior/.local/share/virtualenvs/eos-ZVRZ_kFB/lib/python3.10/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/home/junior/.local/share/virtualenvs/eos-ZVRZ_kFB/lib/python3.10/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/junior/.local/share/virtualenvs/eos-ZVRZ_kFB/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/home/junior/.local/share/virtualenvs/eos-ZVRZ_kFB/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/junior/.local/share/virtualenvs/eos-ZVRZ_kFB/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "court_contacts" does not exist
LINE 1: ...s"."court_id", "court_contacts"."contact_id" FROM "court_con...
`
Here what a have:
I created a multi-type tenants and I have some shared tables and this specific one, Company table, I have a ManyToMany relationship with Contact table. I'm sharing the serializer to mitigate duplicated code too. So, I created a generic one to provide this serialization. But, even when I try to create a private one serialazer to this ModelViewSet (Company), I'm getting the same result.

This other table, CourtContacts, is a private table to a specific tenant type and when I use the Company table from other tenant I get this error message. So, I do no what to do.

I'll share some piece of my code here:
This is INSTALL APPS:

`
HAS_MULTI_TYPE_TENANTS = True
MULTI_TYPE_DATABASE_FIELD = 'type'

TENANT_TYPES = {
    "sistema_panteu_public": {
        "APPS": [
            'django_tenants',
            'eosManager',
            'django.contrib.auth',
            'django.contrib.contenttypes',
            'django.contrib.sessions',
            'django.contrib.messages',
            'django.contrib.staticfiles',
            'rest_framework',
            'django_filters',
            'corsheaders',
            'drf_yasg',
            'drf_api_logger',
        ],
        "URLCONF": "eos.urls_public",
    },
    "broker": {
        "APPS": [
            'django.contrib.contenttypes',
            'django.contrib.auth',
            'django.contrib.sessions',
            'django.contrib.messages',
            'rest_framework',
            'django_filters',
            'corsheaders',
            'drf_yasg',
            'eosBroker',
            'eosShared',
        ],
        "URLCONF": "eos.urls_broker",
        "AUTH_USER_MODEL": 'eosBroker.User',
    },
    "panteu": {
        "APPS": [
            'django.contrib.contenttypes',
            'django.contrib.auth',
            'django.contrib.admin',
            'django.contrib.sessions',
            'django.contrib.messages',
            'rest_framework',
            'django_filters',
            'corsheaders',
            'drf_yasg',
            'eosPanteu',
            'eosShared',
        ],
        "URLCONF": "eos.urls_panteu",
        "AUTH_USER_MODEL": 'eosPanteu.User',
    }
}

INSTALLED_APPS = []
for schema in TENANT_TYPES:
    INSTALLED_APPS += [app for app in TENANT_TYPES[schema]["APPS"] if app not in INSTALLED_APPS]

TENANT_MODEL = "eosManager.Tenant"

TENANT_DOMAIN_MODEL = "eosManager.Domain"

AUTHENTICATION_BACKENDS = ["eos.utils.backends.EosBackend"]
`

This is my CompanyTable

`
from django.db import models, connection
from django.utils.translation import gettext_lazy as _
from storages.backends.s3boto3 import S3Boto3Storage

from eos.utils.models import DefaultModel
from eos.utils.dictionary import *

from eos.choices import CompanyType, OperationalType

class Company(DefaultModel):

    person = models.ForeignKey(
        "eosManager.Person",
        verbose_name=_("Person"),
        on_delete=models.RESTRICT,
        related_name="companies",
        help_text=_(
           EOS_PERSON
        )
    )

    contacts = models.ManyToManyField(
        "eosShared.Contact",
        related_name="companies",
        blank=True,
        verbose_name=_('Contacts'),
        help_text=_(
            EOS_CONTACTS
        )
    )

    type = models.CharField(
        _("Company type"),
        choices=OperationalType.choices,
        default=OperationalType.client,
        help_text=_(
            EOS_TYPE
        )
    )

    email = models.EmailField(
        _('Email'),
        max_length=255,
        null=True,
        blank=True,
        help_text=_(
            EOS_EMAIL
        )
    )

    parent = models.ForeignKey(
        'self',
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name="children",
        verbose_name=_('Company'),
        help_text=_(
            EOS_PARENT
        )
    )

    company_type = models.CharField(
        _('Client type'),
        max_length=100,
        choices=CompanyType.choices,
        default=CompanyType.matrix,
        help_text=_(
            EOS_COMPANY_TYPE
        )
    )

    avatar = models.ImageField(
        _('Avatar'),
        upload_to='client_avatars',
        null=True,
        blank=True,
        storage=S3Boto3Storage(location=connection.schema_name),
        help_text=_(
            EOS_AVATAR
        )
    )

    website = models.CharField(
        _('Website'),
        max_length=255,
        blank=True,
        null=True,
        help_text=_(
            EOS_SITE
        )
    )

    susep = models.CharField(
        'SUSEP',
        max_length=100,
        null=True,
        blank=True,
        help_text=_(
            EOS_SUSEP
        )
    )

    is_active = models.BooleanField(
        _('Is active'),
        default=True,
        help_text=_(
            EOS_IS_ACTIVE
        )
    )

    class Meta:
        verbose_name = _("Company")
        verbose_name_plural = _("Companies")
        db_table = 'company'

`

**Comment by tomturner** [comment]
Closing as part of a backlog tidy-up — not because the report was wrong, but because it can no longer be acted on as it stands.

This has been inactive for some years and a great deal has changed underneath it: `clone_schema` has been replaced wholesale from upstream pg-clone-schema, psycopg3 is now the default driver, and the supported range is Django 4.2 / 5.2 / 6.0 on PostgreSQL 14–17. There's a fair chance this no longer reproduces.

If it still happens on **3.12.0**, please reopen with the django-tenants and Django versions, the PostgreSQL version, and the steps to reproduce — with that I can actually chase it down.

Thanks for reporting it.
